# This is free software, licensed under the Apache License, Version 2.0 .

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Freifunk Berlin configuration wizard
LUCI_DEPENDS:=+luci-base +luci-compat +luci-mod-admin-full +freifunk-policyrouting +luci-lib-jsonc +community-profiles +luci-lib-ipkg

include ../../../luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
